---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-chp-svc
spec:
  selector:
    app: configurable-http-proxy
  clusterIP: "10.104.184.140"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: chp-public
  - protocol: TCP
    port: 8001
    targetPort: 8001
    name: chp-api
