---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
      name: jupyterhub
    spec:
      hostname: jupyterhub-cs-aalto-fi
      containers:
      - name: jupyterhub
        image: jupyterhub-cs
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: jupyterhub-config
          mountPath: /srv/jupyterhub/jupyterhub_config.py
          subPath: jupyterhub_config.py
        - name: jupyter-nfs-course
          mountPath: /m/jupyter/course/
        imagePullPolicy: Never
      tolerations:
      - key: jupyterhub
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: jupyterhub-config
        configMap:
          name: jupyterhub-config
      - name: jupyter-nfs-course
        nfs:
          server: jupyter-k8s-admin.cs.aalto.fi
          path: /srv/jupyter-tw/course/
      nodeSelector:
        app: jupyterhub
      serviceAccountName: jupyter-notebook-spawner
