apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-config
data:
  config: |-
    c.JupyterHub.ip = '0.0.0.0'
    c.JupyterHub.port = 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: jupyterhub/jupyterhub
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: jupyterhub-config
          mountPath: /srv/jupyterhub/jupyterhub_config.py
          subPath: config
      tolerations:
      - key: jupyterhub
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: jupyterhub-config
        configMap:
          name: jupyterhub-config
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-svc
spec:
  selector:
    app: jupyterhub
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
