---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
      name: jupyterhub
    spec:
      hostname: jupyterhub-cs-aalto-fi
      containers:
      - name: jupyterhub
        image: jupyterhub-cs
        ports:
#        - containerPort: 8000
        - containerPort: 8081
        - containerPort: 36541
        env:
        - name: TZ
          value: Europe/Helsinki
#        - name: NO_AD_JOIN
#          value: "true"
        - name: CONFIGPROXY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: chp-secret
              key: chp-secret.txt
        volumeMounts:
        - name: jupyterhub-hubdata
          mountPath: /srv/jupyterhub/
        - name: jupyterhub-config
          mountPath: /srv/jupyterhub/jupyterhub_config.py
          subPath: jupyterhub_config.py
        - name: jupyterhub-course-list
          mountPath: /courses/
        - name: chp-secret
          mountPath: /srv/jupyterhub/chp-secret.txt
          subPath: chp-secret.txt
          readOnly: true
        #- name: jupyterhub-coursedata
        #  mountPath: /coursedata/
        - name: adpw
          mountPath: /etc/adpw.txt
          subPath: adpw.txt
          readOnly: true
        - name: localusers
          mountPath: /etc/localusers.sh
          subPath: localusers.sh
          readOnly: true
        - name: hub-status-service
          mountPath: /srv/jupyterhub/hub_status_service.py
          subPath: hub_status_service.py
        - name: spawn-test
          mountPath: /srv/jupyterhub/spawn_test.py
          subPath: spawn_test.py
#        - name: idrsa
#          mountPath: /root/.ssh/id_rsa
#          subPath: id_rsa_hub
#        - name: idrsapub
#          mountPath: /root/.ssh/id_rsa.pub
#          subPath: id_rsa_hub.pub
#        - name: knownhosts
#          mountPath: /root/.ssh/known_hosts
#          subPath: known_hosts
        imagePullPolicy: Never
      tolerations:
      - key: jupyterhub
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: jupyterhub-hubdata
        nfs:
          server: jhnas.org.aalto.fi
          path: /vol/jupyter/admin/hubdata/
      - name: jupyterhub-config
        configMap:
          name: jupyterhub-config
      - name: chp-secret
        secret:
          secretName: chp-secret
      - name: jupyterhub-course-list
        nfs:
          server: jhnas.org.aalto.fi
          path: /vol/jupyter/course/
      #- name: jupyterhub-coursedata
      #  nfs:
      #    server: jhnas.org.aalto.fi
      #    path: /vol/jupyter/course/coursedata/
      - name: adpw
        secret:
          secretName: adpw.txt
      - name: localusers
        secret:
          secretName: localusers
      - name: idrsa
        secret:
          secretName: idrsa
      - name: idrsapub
        secret:
          secretName: idrsapub
      - name: knownhosts
        secret:
          secretName: knownhosts
      - name: hub-status-service
        configMap:
          name: hub-status-service
      - name: spawn-test
        configMap:
          name: spawn-test
      nodeSelector:
        app: jupyterhub
      serviceAccountName: jupyter-notebook-spawner
