apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-config
data:
  config: |-
    c.JupyterHub.ip = '0.0.0.0'
    c.JupyterHub.port = 8000
    c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
    c.JupyterHub.cleanup_servers = False
    c.KubeSpawner.start_timeout = 60 * 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: jupyterhub-mlbp
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: jupyterhub-config
          mountPath: /srv/jupyterhub/jupyterhub_config.py
          subPath: config
        imagePullPolicy: Never
      tolerations:
      - key: jupyterhub
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: jupyterhub-config
        configMap:
          name: jupyterhub-config
      nodeSelector:
        app: jupyterhub
      serviceAccountName: jupyter-notebook-spawner
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-svc
spec:
  selector:
    app: jupyterhub
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyter-notebook-spawner
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-notebook-spawner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notebook-spawner-binding
roleRef:
  name: jupyter-notebook-spawner
  kind: Role
  apiGroup: ""
subjects:
- kind: User
  name: jupyter-notebook-spawner
  apiGroup: ""
