apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notebook-network-policy
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
