---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-test-nfs-pv
spec:
  capacity:
    # Capacity doesn't really matter, not used. Just make it match the
    # pvc.
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "jupyter-nfs-class"
  mountOptions:
    # - hard
    - nfsvers=3
  nfs:
    server: jhnas.org.aalto.fi
    path: /vol/jupyter/jupyter-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-nfs
  namespace: jupyter-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "jupyter-nfs-class"
  resources:
    requests:
      storage: 100Gi
---
